name: workload-identity-federation
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install 
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: WhoAmI
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ENVIRONMENT_URL
          app-id: APP_ID
          tenant-id: TENANT_ID
