name: workload-identity-federation
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Grant permissions to the OIDC endpoint for federation
    steps:
      - uses: actions/checkout@v4      
      - name: InstallPowerPlatformActions
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          add-tools-to-path: true
      - name: WhoAmI
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
      - name: CreatePowerPlatformCLIAuthProfile
        run: |
          pac auth create --name actions-temp --githubFederated --tenant ${{ secrets.TENANT_ID }} --applicationId ${{ secrets.APP_ID }} --environment ${{ secrets.ENVIRONMENT_URL }}
      - name: UsePowerPlatformCLI
        run: |
          pac env who
